[package]
name = "htmlbuilder"
version = "0.1.0"
edition = "2024"
description = "Build html flexibly and easily in Rust"
license = "MIT"
repository = "https://github.com/Smart-Space/rustHtmlBuilder"

[dependencies]
